### PR TITLE
Fix auto-bump version patterns for README

### PR DESCRIPTION
**Pull request by akaihola**

### CODE REVIEW

**Comment by akaihola** [comment]
Hi @ire4ever1190,

This PR makes a correction to the regular expression pattern which was supposed to correctly update all Graylint version strings in documentation when the `graylint_bump_version` script is run (the script comes from [darkgray-dev-tools](/akaihola/darkgray-dev-tools?tab=readme-ov-file#darkgray_bump_version)). The `v` prefix was missing, and the whole rule was incorrectly indented in the YAML file.

I invited you as a collaborator on this repository, so if you're interested to review this small fix, I can assign you as reviewer for this PR. Thanks again for your contribution on #62!

**Comment by ire4ever1190** [comment]
Ah, sorry for not catching that in my original PR. 
Yes you can assign me to the PR, happy to review

**Comment by akaihola** [comment]
> Yes you can assign me to the PR, happy to review

I can do that once you accept the collaborator invitation.

**Comment by ire4ever1190** [comment]
Apologies, thought I accepted. Invite should be accepted now

**Review by ire4ever1190 — APPROVED** [review]

**Pull request merged**
